[package]
name = "webrusty"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2.92"

[lib]
crate-type = ["cdylib"]

[dependencies.web-sys]
version = "0.3"
features = [
    'Window',
    'Document',
    'HtmlElement',
    'EventTarget',
    'WebSocket',
    'MessageEvent',
    'HtmlInputElement',
    'HtmlFormElement',
    'console',
]
